# Generated by Django 5.0.1 on 2024-04-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(
                choices=[('general_user', 'General User'), ('admin', 'Admin'), ('MODERATOR', 'Moderator')],
                default='general_user', max_length=31, verbose_name='User Type'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
