# Generated by Django 5.0.1 on 2024-04-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_user_user_type_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('general_user', 'General User'), ('admin', 'Admin'), ('MODERATOR', 'Moderator')],
                default='general_user', max_length=31, verbose_name='Role'),
        ),
    ]
