name: relief_tracker
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  dio: ^5.3.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.0.0
  google_maps_flutter: ^2.2.8
  json_annotation: ^4.8.1
  package_info_plus: ^4.1.0
  platform_info: ^4.0.2
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.2.1
  uuid: ^4.1.0
  dropdown_search: ^5.0.6
  image_picker: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  json_serializable: ^6.7.1
  lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    # - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

