# Generated by Django 5.0.1 on 2024-02-29 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('disaster', '0001_initial'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations',
                                               to='disaster.disaster', verbose_name='Disaster')),
                ('donors',
                 models.ManyToManyField(related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='Donors')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonatedUpazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('donated_people', models.PositiveIntegerField(verbose_name='Donated People')),
                ('upazila',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_upazilas',
                                   to='location.upazila', verbose_name='Upazila')),
                ('donation',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_upazilas',
                                   to='donation.donations', verbose_name='Donation')),
            ],
            options={
                'verbose_name': 'Donated Upazila',
                'verbose_name_plural': 'Donated Upazilas',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonatedUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('donated_people', models.PositiveIntegerField(verbose_name='Donated People')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_unions',
                                            to='location.union', verbose_name='Union')),
                ('donation',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_unions',
                                   to='donation.donations', verbose_name='Donation')),
            ],
            options={
                'verbose_name': 'Donated Union',
                'verbose_name_plural': 'Donated Unions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonatedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('quantity', models.FloatField(default=0, verbose_name='Quantity')),
                ('unit', models.CharField(max_length=100, verbose_name='Unit')),
                ('donation',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_items',
                                   to='donation.donations', verbose_name='Donation')),
            ],
            options={
                'verbose_name': 'Donated Item',
                'verbose_name_plural': 'Donated Items',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonatedDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('donated_people', models.PositiveIntegerField(verbose_name='Donated People')),
                ('district',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_districts',
                                   to='location.district', verbose_name='District')),
                ('donation',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_districts',
                                   to='donation.donations', verbose_name='Donation')),
            ],
            options={
                'verbose_name': 'Donated District',
                'verbose_name_plural': 'Donated Districts',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherDonatedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('location', models.TextField(verbose_name='Location')),
                ('donated_people', models.PositiveIntegerField(verbose_name='Donated People')),
                ('donation',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_donated_locations',
                                   to='donation.donations', verbose_name='Donation')),
            ],
            options={
                'verbose_name': 'Other Donated Location',
                'verbose_name_plural': 'Other Donated Locations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
