# Generated by Django 5.0.1 on 2024-02-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateddistrict',
            name='donated_people',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Donated People'),
        ),
        migrations.AlterField(
            model_name='donatedunion',
            name='donated_people',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Donated People'),
        ),
        migrations.AlterField(
            model_name='donatedupazila',
            name='donated_people',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Donated People'),
        ),
        migrations.AlterField(
            model_name='otherdonatedlocation',
            name='donated_people',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Donated People'),
        ),
    ]
