# Generated by Django 5.0.1 on 2024-03-07 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('disaster', '0002_alter_affecteddistrict_affected_people_and_more'),
        ('donation', '0002_alter_donateddistrict_donated_people_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('disaster',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations',
                                   to='disaster.disaster', verbose_name='Disaster')),
                ('donors',
                 models.ManyToManyField(related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='Donors')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='donateddistrict',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_districts',
                                    to='donation.donation', verbose_name='Donation'),
        ),
        migrations.AlterField(
            model_name='donateditems',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_items',
                                    to='donation.donation', verbose_name='Donation'),
        ),
        migrations.AlterField(
            model_name='donatedunion',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_unions',
                                    to='donation.donation', verbose_name='Donation'),
        ),
        migrations.AlterField(
            model_name='donatedupazila',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_upazilas',
                                    to='donation.donation', verbose_name='Donation'),
        ),
        migrations.AlterField(
            model_name='otherdonatedlocation',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_donated_locations',
                                    to='donation.donation', verbose_name='Donation'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('media', models.FileField(upload_to='donation/', verbose_name='Media')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media',
                                               to='donation.donation', verbose_name='Donation')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Donations',
        ),
    ]
