# Generated by Django 5.0.1 on 2024-03-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('donation', '0003_donation_alter_donateddistrict_donation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateditems',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
