# Generated by Django 5.0.1 on 2024-03-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('donation', '0004_donateditems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                                   default='pending', max_length=10, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(
                choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')],
                default='image', max_length=10, verbose_name='Type'),
        ),
    ]
