# Generated by Django 5.0.1 on 2024-03-08 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('donation', '0006_donation_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='added_donations', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Created By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='donors',
            field=models.ManyToManyField(blank=True, related_name='donations', to=settings.AUTH_USER_MODEL,
                                         verbose_name='Donors'),
        ),
    ]
