# Generated by Django 5.0.1 on 2024-03-22 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('donation', '0007_alter_donation_created_by_alter_donation_donors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donateditems',
            name='donation',
        ),
    ]
