# Generated by Django 5.0.1 on 2024-03-22 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('donation', '0008_remove_donateditems_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateditems',
            name='donated_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='donated_items', to='donation.donateddistrict',
                                    verbose_name='Donated District'),
        ),
        migrations.AddField(
            model_name='donateditems',
            name='donated_union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='donated_items', to='donation.donatedunion',
                                    verbose_name='Donated Union'),
        ),
        migrations.AddField(
            model_name='donateditems',
            name='donated_upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='donated_items', to='donation.donatedupazila',
                                    verbose_name='Donated Upazila'),
        ),
        migrations.AddField(
            model_name='donateditems',
            name='other_donated_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='donated_items', to='donation.otherdonatedlocation',
                                    verbose_name='Other Donated Location'),
        ),
    ]
