# Generated by Django 5.0.1 on 2024-03-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('donation', '0009_donateditems_donated_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdonatedlocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='otherdonatedlocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
