# Generated by Django 5.0.1 on 2024-04-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('donation', '0010_otherdonatedlocation_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donateditems',
            name='other_donated_location',
        ),
        migrations.AddField(
            model_name='donateddistrict',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='donatedunion',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='donatedupazila',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='donateddistrict',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donated_districts',
                                       to='donation.donation', verbose_name='Donation'),
        ),
        migrations.AlterField(
            model_name='donatedunion',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donated_unions',
                                       to='donation.donation', verbose_name='Donation'),
        ),
        migrations.AlterField(
            model_name='donatedupazila',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donated_upazilas',
                                       to='donation.donation', verbose_name='Donation'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                                   default='pending', max_length=31, verbose_name='State'),
        ),
    ]
