# Generated by Django 5.0.1 on 2024-04-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('donation', '0011_remove_donateditems_other_donated_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='documents',
            field=models.JSONField(blank=True, default=list, verbose_name='Documents'),
        ),
        migrations.AddField(
            model_name='donation',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='donation',
            name='videos',
            field=models.JSONField(blank=True, default=list, verbose_name='Videos'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
