# Generated by Django 5.0.1 on 2024-04-10 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('donation', '0012_donation_documents_donation_images_donation_videos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherDonatedLocation',
        ),
    ]
