# Generated by Django 5.0.1 on 2024-04-14 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('donation', '0013_delete_otherdonatedlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateddistrict',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_districts',
                                    to='donation.donation', verbose_name='Donation'),
        ),
        migrations.AlterField(
            model_name='donatedunion',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_unions',
                                    to='donation.donation', verbose_name='Donation'),
        ),
        migrations.AlterField(
            model_name='donatedupazila',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_upazilas',
                                    to='donation.donation', verbose_name='Donation'),
        ),
    ]
