# Generated by Django 5.0.1 on 2024-02-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='bangla_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bangla Name'),
        ),
        migrations.AddField(
            model_name='district',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='district',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='union',
            name='bangla_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bangla Name'),
        ),
        migrations.AddField(
            model_name='union',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='union',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='upazila',
            name='bangla_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bangla Name'),
        ),
        migrations.AddField(
            model_name='upazila',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='upazila',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='union',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='upazila',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
