# Generated by Django 5.0.1 on 2024-02-29 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('location', '0002_district_bangla_name_district_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['id'], 'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='union',
            options={'ordering': ['id'], 'verbose_name': 'Union', 'verbose_name_plural': 'Unions'},
        ),
        migrations.AlterModelOptions(
            name='upazila',
            options={'ordering': ['id'], 'verbose_name': 'Upazila', 'verbose_name_plural': 'Upazilas'},
        ),
    ]
