# Generated by Django 5.0.1 on 2024-04-03 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('location', '0004_division_district_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='division',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts',
                                    to='location.division', verbose_name='Division'),
        ),
    ]
