# Generated by Django 5.0.1 on 2024-02-29 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
            ],
            options={
                'verbose_name': 'Disaster',
                'verbose_name_plural': 'Disasters',
                'ordering': ['-start_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AffectedUpazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('affected_people', models.PositiveIntegerField(verbose_name='Affected People')),
                ('upazila',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_upazilas',
                                   to='location.upazila', verbose_name='Upazila')),
                ('disaster',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_upazilas',
                                   to='disaster.disaster', verbose_name='Disaster')),
            ],
            options={
                'verbose_name': 'Affected Upazila',
                'verbose_name_plural': 'Affected Upazilas',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AffectedUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('affected_people', models.PositiveIntegerField(verbose_name='Affected People')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_unions',
                                            to='location.union', verbose_name='Union')),
                ('disaster',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_unions',
                                   to='disaster.disaster', verbose_name='Disaster')),
            ],
            options={
                'verbose_name': 'Affected Union',
                'verbose_name_plural': 'Affected Unions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AffectedDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('affected_people', models.PositiveIntegerField(verbose_name='Affected People')),
                ('district',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_districts',
                                   to='location.district', verbose_name='District')),
                ('disaster',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_districts',
                                   to='disaster.disaster', verbose_name='Disaster')),
            ],
            options={
                'verbose_name': 'Affected District',
                'verbose_name_plural': 'Affected Districts',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherAffectedLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('location', models.TextField(verbose_name='Location')),
                ('affected_people', models.PositiveIntegerField(verbose_name='Affected People')),
                ('disaster',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_affected_locations',
                                   to='disaster.disaster', verbose_name='Disaster')),
            ],
            options={
                'verbose_name': 'Other Affected Location',
                'verbose_name_plural': 'Other Affected Locations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
