# Generated by Django 5.0.1 on 2024-02-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('disaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affecteddistrict',
            name='affected_people',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Affected People'),
        ),
        migrations.AlterField(
            model_name='affectedunion',
            name='affected_people',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Affected People'),
        ),
        migrations.AlterField(
            model_name='affectedupazila',
            name='affected_people',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Affected People'),
        ),
        migrations.AlterField(
            model_name='otheraffectedlocations',
            name='affected_people',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Affected People'),
        ),
    ]
