# Generated by Django 5.0.1 on 2024-03-21 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('disaster', '0002_alter_affecteddistrict_affected_people_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('image', models.ImageField(upload_to='disaster/images/', verbose_name='Image')),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images',
                                               to='disaster.disaster', verbose_name='Disaster')),
            ],
            options={
                'verbose_name': 'Disaster Image',
                'verbose_name_plural': 'Disaster Images',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
